### ISSUE TITLE
Simple knowledge engine ?

### ISSUE THREAD

**Issue by ghost** [KirillOsenkov/MyOwnSearchEngine#1]
Hello,

If I may ask, what's your roadmap with this project ? Are you going to create a basic knowledge engine such as Wolfram is ?

**Comment by KirillOsenkov** [comment]
For now it's just a convenient tool for myself to replace calc.exe, some basic functionality from Excel, a bunch of poor quality unit converters etc. I don't have a lot of ambitions with this, because I'll never be able to compete with Google, Bing, DuckDuckGo and WolframAlpha. 

However I believe that I can make a few core scenarios faster/better, primarily for myself, but maybe for others as well. Right now it's too early, but feel free to keep watching if interested.
